### ISSUE TITLE
Function afterSave() is generated wrong

### ISSUE THREAD

**Issue by hortigado** [GetDutchie/brick#373] opened 2024-03-16 17:46 UTC
Hi i have it problem with the function afterSave with fields type List<Model>. The problem is that the `List<Vaccine> `field to be added as a child relationship when saving the parent document; Generating an error because this field does not exist in the database.
For now I have to manually delete these fields from the `afterSave `function of the generated adapter

Field List added in model parent
```
  @Rest(ignore: true)
  @Sqlite(ignore: true)
  List<Vacccines> vaccines;
```

Adapter generated with it in the method afterSave
```
  Future<void> afterSave(instance, {required provider, repository}) async {
    if (instance.primaryKey != null) {
      final balanceadosOldColumns = await provider.rawQuery(
          'SELECT `f_Vaccine_brick_id` FROM `_brick_CerdasModelServer_balanceados` WHERE `l_CerdasModelServer_brick_id` = ?',
          [instance.primaryKey]);
      final balanceadosOldIds = balanceadosOldColumns
          .map((a) => a['f_Vaccine_brick_id']);
      final balanceadosNewIds =
          instance.balanceados.map((s) => s.primaryKey).whereType<int>();
      final balanceadosIdsToDelete =
          balanceadosOldIds.where((id) => !balanceadosNewIds.contains(id));

      await Future.wait<void>(balanceadosIdsToDelete.map((id) async {
        return await provider.rawExecute(
            'DELETE FROM `_brick_CerdasModelServer_balanceados` WHERE `l_CerdasModelServer_brick_id` = ? AND `f_Vaccine_brick_id` = ?',
            [instance.primaryKey, id]).catchError((e) => null);
      }));

      await Future.wait<int?>(instance.balanceados.map((s) async {
        final id = s.primaryKey ??
            await provider.upsert<Vaccine>(s,
                repository: repository);
        return await provider.rawInsert(
            'INSERT OR IGNORE INTO `_brick_CerdasModelServer_balanceados` (`l_CerdasModelServer_brick_id`, `f_Vaccine_brick_id`) VALUES (?, ?)',
            [instance.primaryKey, id]);
      }));
    }
```

**Comment by hortigado** [comment] 2024-05-06 01:28
Correct, `AfterSave` should return empty but it takes all the `Lists` as relationships, which generates problems because the column was not created as a relationship, therefore the relationship type column does not exist.

**Comment by hortigado** [comment] 2024-05-06 01:30
I solved the problem by adding late to the List and in the build ignoring when the field `isLate` but it is not a clean and correct solution

**Comment by tshedor** [comment] 2024-05-27 19:24
@hortigado I've put together a small reproduction of your issue and, as far as I can see, the `@Sqlite(ignore: true)` fields are ignored. 

Please [examine this branch](https://github.com/GetDutchie/brick/compare/373-after-save-demo?expand=1) and let me know where your issue differs.

**Comment by tshedor** [comment] 2024-06-09 21:40
Hi @hortigado wanted to tap you again. Have you tried that branch?

**Comment by hortigado** [comment] 2024-06-12 19:44
@tshedor Hello, I just made a new project to test and indeed the problem does not exist. In my case it doesn't work because before the list was an association and I changed it to a simple list. That's why I think he now takes it as an association even though it isn't. In some free time I will review what is not deleted and continues to take the list as an association.

**Comment by tshedor** [comment] 2024-07-02 01:51
@hortigado Cool, I'll close this out but please comment back if it needs to be reopened

**Closed by tshedor** 2024-07-02 01:51 UTC

**Comment by hortigado** [comment] 2024-12-11 17:02
Hello again, are the migrations saved as cache in some path on the PC? Because I keep having this problem in existing projects that worked with associations and the lists are changed to empty with `ignore: true `and the adapter is still generated as an association. I have tried deleting folders like` .dart_tool `since I saw that the models are saved there but it does not solve the problem.

**Comment by tshedor** [comment] 2024-12-11 23:20
@hortigado I'm not sure what you mean. I wasn't able to replicate this a few months ago.

Are you able to provide a small, reproducible example? There's no caching as far as I'm aware but I'm unfamiliar with using Brick on Windows

**Comment by hortigado** [comment] 2024-12-12 01:30
![image](https://github.com/user-attachments/assets/2dcd6847-b8b8-4487-83ef-eedb66401d61)
![image](https://github.com/user-attachments/assets/64f2ec20-ae10-4d5c-a253-32c48a30ae69)

@tshedor  After months with the problem XD, I managed to reproduce the problem . Which is generated by adding toJson and fromJson to our model. The solution would be to add toMap and fromMap if we need to play with the model or you think it's wrong. Regards

**Comment by tshedor** [comment] 2024-12-12 17:08
@hortigado based on that screenshot, you're not ignoring any fields, which [I thought is what you were trying to avoid](https://github.com/GetDutchie/brick/issues/373#issuecomment-2095045421)? It looks like all you're trying to do is to never deserialize `toppings`]?

Based on your previous comments, the problem you're experiencing is around the associations being generated in `afterSave`, but none of the fields in the example class include an association

**Comment by tshedor** [comment] 2024-12-12 17:29
> Convert the association to a list (remove https://github.com/offlinefirst(where:))

`@OfflineFirst(where:)` actually only generates REST code. It doesn't affect the SQLite generation. 

What does affect SQLite generation is the class type. So if you're doing this:  

> Add toJson and fromJson to the model (Problem generator)

Without changing the class of the model to an `OfflineFirstSerdes` then it's going to generate as an association. Can you try changing the class type to an `OfflineFirstSerdes` instead?

**Comment by hortigado** [comment] 2024-12-12 17:48
@tshedor Indeed `OfflineFirstSerdes` is the solution. I had tried with other types of classes, but not with this one because I thought it was for another purpose. Thanks friend, it is the definitive solution (y). Good day

**Comment by tshedor** [comment] 2024-12-12 18:49
@hortigado Ah great. Ok let me know if you hit any other bugs
